### ISSUE TITLE
iobroker restore 0 with TypeError: name.trim is not a function

### ISSUE THREAD

**Issue by SayAndre** [ioBroker/ioBroker#170]
I think I discovered an issue with the iobroker restore 0 function.
I just tested it on a debian system and raspberry with raspbian stretch lite.

Both times following error:
Raspberry:
Node.js: v8.15.0
NPM: 6.4.1

What makes it confusing for me, this iobroker ( on the raspberray ) was just configured with an older backup.

```
root@raspberrypi:~# cd /opt/iobroker/
root@raspberrypi:/opt/iobroker# sudo iobroker backup
Backup created: /opt/iobroker/backups/2019_06_08-15_32_42_backupiobroker.tar.gz
root@raspberrypi:/opt/iobroker# sudo iobroker stop
root@raspberrypi:/opt/iobroker# sudo iobroker restore 0
/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:568
        if (parseInt(name.trim(), 10).toString() === name.trim().toString()) {
                          ^

TypeError: name.trim is not a function
    at BackupRestore.restoreBackup (/opt/iobroker/node_modules/iobroker.js-contr                                                                                                                                                             oller/lib/setup/setupBackup.js:568:27)
    at dbConnect (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js                                                                                                                                                             :1474:28)
    at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/lib/s                                                                                                                                                             etup.js:3061:29)
    at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller                                                                                                                                                             /lib/objects/objectsInMemServer.js:3393:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
root@raspberrypi:/opt/iobroker# sudo iobroker start
root@raspberrypi:/opt/iobroker#

```

Beelink BT3 Pro ( Debian 9.9 ):
Js-controller Version: 1.5.12
Node.js: v8.16.0
NPM: 6.9.0

`root@debianiobroker:/opt/iobroker# iobroker restore 0
/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:568
if (parseInt(name.trim(), 10).toString() === name.trim().toString()) {
^
TypeError: name.trim is not a function
at BackupRestore.restoreBackup (/opt/iobroker/node_modules/iobroker.js-contr oller/lib/setup/setupBackup.js:568:27)
at dbConnect (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js :1474:28)
at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/lib/s etup.js:3087:29)
at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller /lib/states/statesInMemServer.js:184:26)
at runCallback (timers.js:810:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)`

**Comment by SayAndre** [comment]
Issue solved.
Edit the /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js
in line 568 & 571 regarding trim() function ( just delete it )

somehow this file is not getting updated even with the latest js-controller. please fix that!

**Comment by Apollon77** [comment]
But why closed? Is the error also existing in GitHub version? Please check the 1.5.x branch.
