### ISSUE TITLE
Problem mit Bunuzer

### ISSUE THREAD

**Issue by rys800** [ioBroker/ioBroker#377]
2instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.501acaca.chunk.js:2:5595786)
    at 6.501acaca.chunk.js:2:5600621
    at Po (6.501acaca.chunk.js:2:5611663)
    at Zi (6.501acaca.chunk.js:2:5657695)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at s.m.setState (6.501acaca.chunk.js:2:5664084)
    at 9.a078e0d6.chunk.js:1:27236
(anonymous) @ instrument.ts:125
DevTools failed to load source map: Could not load content for chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by Apollon77** [comment]
This is an admin issue (and I think Issue already exists, so close here. Please Check the ioBroker/ioBroker.admin repo
