### ISSUE TITLE
Error on :8081/#tab-users in iobroker v5.3.1

### ISSUE THREAD

**Issue by Mart53** [ioBroker/ioBroker#379]
Just installed iobroker new, when clicking on "Users" I get the following error:

index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-03-20T16:08:15.822Z] Try to connect
instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22
(anonymous) @ instrument.ts:125
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ UsersList.js:331
Promise.then (async)
o.updateData @ UsersList.js:329
(anonymous) @ UsersList.js:297
pc @ react-dom.production.min.js:131
gi @ react-dom.production.min.js:220
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22
(anonymous) @ instrument.ts:125
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ UsersList.js:331
Promise.then (async)
o.updateData @ UsersList.js:329
(anonymous) @ UsersList.js:297
pc @ react-dom.production.min.js:131
gi @ react-dom.production.min.js:220
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12

**Comment by Apollon77** [comment]
duplicate #1337

**Comment by Mart53** [comment]
Thank you Appollon77 did not see that the issue is already known.
