### ISSUE TITLE
iobroker fixer fehler

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker#408]
Hallo,

Fehler beim ausführen von iobroker fixer:

`Microsoft Windows [Version 10.0.19045.2251]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Privat>cd..

C:\Users>cd..

C:>cd iobroker

C:\ioBroker>npm x @iobroker/fix
"(" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

C:\ioBroker>npm x @iobroker/fix@latest
"(" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

C:\ioBroker>`

**Comment by Apollon77** [comment]
Und wenn falsches Verzeichnis:

```


NPM: 8.19.2

C:\Users>cd..

C:>npm x @iobroker/fix
NPM version: 8.19.2
node:internal/fs/utils:347
throw err;
^

Error: EPERM: operation not permitted, mkdir 'C:'
at Object.mkdirSync (node:fs:1382:3)
at Object.module.exports.makeDirSync (C:\Users\Privat\AppData\Local\npm-cache_npx\19d197aa1f8fa98c\node_modules\fs-extra\lib\mkdirs\make-dir.js:23:13)
at Object.copyFilesRecursiveSync (C:\Users\Privat\AppData\Local\npm-cache_npx\19d197aa1f8fa98c\node_modules@iobroker\fix\lib-npx\tools.js:610:12)
at copyFilesToRootDir (C:\Users\Privat\AppData\Local\npm-cache_npx\19d197aa1f8fa98c\node_modules@iobroker\fix\lib-npx\installCopyFiles.js:35:11)
at Object.<anonymous> (C:\Users\Privat\AppData\Local\npm-cache_npx\19d197aa1f8fa98c\node_modules@iobroker\fix\lib-npx\installCopyFiles.js:14:1)
at Module._compile (node:internal/modules/cjs/loader:1155:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
at Module.load (node:internal/modules/cjs/loader:1033:32)
at Function.Module._load (node:internal/modules/cjs/loader:868:12)
at Module.require (node:internal/modules/cjs/loader:1057:19) {
errno: -4048,
syscall: 'mkdir',
code: 'EPERM',
path: 'C:\'
}

C:>

Need to install the following packages:
@iobroker/fix@4.2.0
Ok to proceed? (y) y
Windows installation starting... (fixing = true)
NPM version: 8.19.2
node:internal/fs/utils:347
throw err;
^

Error: EPERM: operation not permitted, mkdir 'C:'
at Object.mkdirSync (node:fs:1382:3)
at Object.module.exports.makeDirSync (C:\Users\Privat\AppData\Local\npm-cache_npx\41f6637076e42190\node_modules\fs-extra\lib\mkdirs\make-dir.js:23:13)
at Object.copyFilesRecursiveSync (C:\Users\Privat\AppData\Local\npm-cache_npx\41f6637076e42190\node_modules@iobroker\fix\lib-npx\tools.js:612:12)
at copyFilesToRootDir (C:\Users\Privat\AppData\Local\npm-cache_npx\41f6637076e42190\node_modules@iobroker\fix\lib-npx\installCopyFiles.js:35:11)
at Object.<anonymous> (C:\Users\Privat\AppData\Local\npm-cache_npx\41f6637076e42190\node_modules@iobroker\fix\lib-npx\installCopyFiles.js:14:1)
at Module._compile (node:internal/modules/cjs/loader:1155:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
at Module.load (node:internal/modules/cjs/loader:1033:32)
at Function.Module._load (node:internal/modules/cjs/loader:868:12)
at Module.require (node:internal/modules/cjs/loader:1057:19) {
errno: -4048,
syscall: 'mkdir',
code: 'EPERM',
path: 'C:\'
}

C:>

```

**Comment by Gaspode69** [comment]
Ursache für den Fehler 
`"(" kann syntaktisch an dieser Stelle nicht verarbeitet werden.`
ist, dass der Aufruf
`npx @iobroker/fix`
aus irgendeinem Grund iobroker.bat ausführt.
Löscht man testweise iobroker.bat, funktioniert anschließen das Ausführen des Fixers.
iobroker.bat wird übrigens vom Fixer gleich wieder angelegt. ;-)

**Comment by Apollon77** [comment]
Iiinteressant ... wartum verstehe ich aber ebenso nicht ... irgendeine Idee wie/ob man in die bat was einbauen könnte was das fixt? bzw kann es sein das es der versuch ist iobroker zu stoppen?

**Comment by Gaspode69** [comment]
Für mich sieht es so aus, als ob die Batchdatei ohne Umwege sofort ausgeführt wird. Ich habe keinen Plan warum.
Durch Änderungen an der Batchdatei wird man das nicht lösen können, befürchte ich. Die Frage ist, warum die anstelle der Package ausgeführt wird. Einfachster Workaround: Schlachten von iobroker.bat und nutzen von iob.bat. Das will aber wohl niemand wirklich.

**Comment by Apollon77** [comment]
Kannst mal schauen welche parameter kommen? Vllt kann man nen workaround da einbauen das der in dem fall dann auch das npx macht oder so?

**Comment by Gaspode69** [comment]
Der Installer löscht übrigens als Workaround iobroker.bat, bevor er den Fixer startet. Wie weiter oben geschrieben, wird iobroker.bat dann wieder durch den Fixer angelegt.
