### ISSUE TITLE
Windows: iobroker fixer starts iobroker before starting the data compression

### ISSUE THREAD

**Issue by Gaspode69** [ioBroker/ioBroker#422]
Logfile:
```
F:\ioBrokerTest>npx @iobroker/fix
Windows installation starting... (fixing = true)
NPM version: 9.3.0
Write "iobroker start" to start the ioBroker
npm install node-windows@1.0.0-beta.8 --force --loglevel error --production --save --prefix "F:/ioBrokerTest"
up to date, audited 524 packages in 6s
36 packages are looking for funding
  run `npm fund` for details
20 vulnerabilities (15 moderate, 5 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
=============================
Running Admin shell
=============================
ioBroker wird beendet.
ioBroker wurde erfolgreich beendet.
ioBroker service is already installed.
=============================
Running Admin shell
=============================
ioBroker wird gestartet.
ioBroker wurde erfolgreich gestartet.
ioBroker service installed and started. Go to http://localhost:8081 to open the admin UI.
To see the outputs do not start the service, but write "node node_modules/iobroker.js-controller/controller"
NPM version: 9.3.0
No path given, using F:\ioBrokerTest\iobroker-data
Compressing F:\ioBrokerTest\iobroker-data\states.jsonl
Cannot compress states.jsonl: Error: Failed to lock DB file "F:\ioBrokerTest\iobroker-data\states.jsonl"!
    at JsonlDB.open (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@alcalzone\jsonl-db\build\lib\db.js:185:19)
    at async compressDB (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@iobroker\jsonltool\index.js:37:9)
    at async main (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@iobroker\jsonltool\index.js:78:17)
Compressing F:\ioBrokerTest\iobroker-data\objects.jsonl
Cannot compress objects.jsonl: Error: Failed to lock DB file "F:\ioBrokerTest\iobroker-data\objects.jsonl"!
    at JsonlDB.open (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@alcalzone\jsonl-db\build\lib\db.js:185:19)
    at async compressDB (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@iobroker\jsonltool\index.js:37:9)
    at async main (C:\Users\ONKELA~1\AppData\Local\npm-cache\_npx\36bee06d4228a674\node_modules\@iobroker\jsonltool\index.js:93:17)
No relevant JSONL files found to compress, skip
```

**Comment by Apollon77** [comment]
please retzry with 4.2.2 once released (and make sure to add a @latest at the end of the npm command to really get the newest version

**Comment by Apollon77** [comment]
released
