### ISSUE TITLE
thousands of errors "empty object" when restarting javascript.0

### ISSUE THREAD

**Issue by peperoni60** [ioBroker/ioBroker#495]
When restarting javascript.0 (or any other instance of javascript) I get thousands of errors "empty object" in the log file. After a while, the instance calms down and runs normally. The console log shows following errors:
```
Sent ready, but not all handlers installed!
Sent ready, but not all handlers installed!
Sent ready, but not all handlers installed!
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [system.adapter.javascript.0.logging]
[ioredis] Unhandled error event: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:931:11)
    at Socket._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at Redis.scan (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)
    at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:679:33)
    at ScanStream._read (/opt/iobroker/node_modules/ioredis/built/ScanStream.js:36:41)
    at ScanStream.Readable.read (node:internal/streams/readable:496:12)
    at maybeReadMore_ (node:internal/streams/readable:650:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: DB closed
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:323:12)
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [system.adapter.javascript.0.logging]
```
Each time I change a script in the `global` folder, the instance restarts and locks me from working in iobroker until the instance has started.

I have restarted the iobroker container and the whole docker stack, but that didn't help.

I'm running a docker stack of 
* influxdb:latest
* buanet/iobroker:latest-v8
* redis/latest

The javscript-Adapter version is: v7.1.6

**Comment by Apollon77** [comment]
Chack your redis instance, seems like the redis has issues. For such more support like cases please write in ioBroker Forum
