### ISSUE TITLE
"objects" tab not accessible

### ISSUE THREAD

**Issue by ahnungsbefreit** [ioBroker/ioBroker#584]
Using ioBroker for several years without any major problem, I ran into an issue recently I cannot resolve myself:

ioBroker is running on Debian VM under Proxmox with ample resources (6G RAM, 64G SSD, 2 cores) for quite some time. It is still working (scripts, VIS etc.) and I can also access the admin page. But when trying to open the "objects" tab, I end up with an endless animation (small rotating circle in the left upper corner) and no display at all of the objects pages (e.g. the header with filters is not showing up).

What I tried to solve the problem:

- Using different browsers (chrome, firefox, edge)
- DIfferent devices (desktop, mobile)
- Cleaning the browser cache and private mode
- Restart iobroker and the VM
- `iob stop/fix/start`
- Creating a new VM (debian bookworm) and restore my setup via "Backitup"
- Of course proxmox, the VM and iobroker have all of the latest STABLE updates
- `iob upload all`

The only suspicious message I found in the browser console is something like
`helpers.ts:120 Uncaught TypeError: Cannot read properties of undefined (reading 'alias')
    at M (ObjectBrowser.tsx:1641:55)
    at ObjectBrowser.tsx:3937:40
    at r (helpers.ts:98:17)`
appearing multiple time after several mintues of waiting.
[2024-11-04 iob diag.txt](https://github.com/user-attachments/files/17615995/2024-11-04.iob.diag.txt)

Full diag attached, any hint how to solve this appreciated! To me, this looks like something is broken in the code rendering the "objects" page.

**Comment by ahnungsbefreit** [comment]
I kept on digging and it seems like the Alias Manager created the mess. After some clean-up of the Aliases (and re-creating some of them to ensure they are properly defined) I only see on alias left in the "Devices" tab, all other disappeared. And the "objects" tab still does not work at all... Any hint what is wrong with the alias definition? And is there any way to extract all alias defs and correct them with a file editor?

**Comment by ahnungsbefreit** [comment]
Update: Issue solved. It turned out that the fact I had one Alias name with an Umlaut in it ("Küche") created the issue, although this worked before. By just renaming this branch to "Kueche" with the help of Alias Manager, the problem disappeared. I suggest to make the code rendering the objects tab more robust for such cases....
