### ISSUE TITLE
Cannot find module "has-binary2"

### ISSUE THREAD

**Issue by christianhunewald** [ioBroker/ioBroker#82]
[iobroker.2018-12-22.log](https://github.com/ioBroker/ioBroker/files/2705512/iobroker.2018-12-22.log)

Just installed ioBroker on operating system 10.14.1 macOS. I can reach web-interface through http://localhost:8081, but getting the following error message (see attached complete log file as well.)

Please could somebody help me?

Regards
Christian

2018-12-22 21:02:50.956 - info: cloud.0 terminating
2018-12-22 21:02:50.962 - error: Caught by controller[0]: { Error: Cannot find module 'has-binary2'
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:529:25)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:657:17)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at require (internal/modules/cjs/helpers.js:22:18)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Object. (/Users/christianhunewald/Documents/iobroker/node_modules/iobroker.cloud/node_modules/engine.io-parser/lib/index.js:6:17)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:721:30)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:620:32)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
2018-12-22 21:02:50.962 - error: Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:552:3) code: 'MODULE_NOT_FOUND' }
2018-12-22 21:02:50.963 - error: host.Yvonnes-MBP.fritz.box instance system.adapter.cloud.0 terminated with code 0 (OK)
2018-12-22 21:02:50.963 - info: host.Yvonnes-MBP.fritz.box Restart adapter system.adapter.cloud.0 because enabled

**Comment by AlCalzone** [comment]
I think this is supposed to be in the iobroker.cloud repo

**Comment by Apollon77** [comment]
Maybe a sub-dep from cloud deps :-(
Hm installog says nothing that it is missng a dependency.

try 

npm install has-binary2 --production

in the iobroker directory

Never saw such a problem

**Comment by Apollon77** [comment]
Strange ...
